services:
  accounts:
    image: jfrg28/accounts:v1
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - pacobank-network
  loans:
    image: jfrg28/loans:v1
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - pacobank-network
  cards:
    image: jfrg28/cards:v1
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - pacobank-network
networks:
  pacobank-network:
    driver: "bridge"
