package com.eazybytes.accounts.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Pattern;
import lombok.Data;

@Data
@Schema(
        name = "Account",
        description = "Schema to hold Account information"
)
public class AccountDto {

    @Schema(
            description = "Account number linked to the customer. Autogenerated",
            example = "1234567890"
    )
    @NotEmpty(message = "Account number can't be a null or empty.")
    @Pattern(regexp = "(^$[0-9]{10})",message = "Account number must be 10 digits. Numbers only.")
    private Long accountNumber;

    @Schema(
            description = "Account type of a PacoBank account",
            example = "Savings"
    )
    @NotEmpty(message = "Account type number can't be a null or empty.")
    private String accountType;

    @Schema(
            description = "Branch address of a PacoBank account",
            example = "123 Paris, France"
    )
    @NotEmpty(message = "Branch address can't be a null or empty.")
    private String branchAddress;

}
